INSERT INTO sales_team_members (name, email, phone, designation) VALUES ('Norma Fisher', 'ysullivan@yahoo.com', '9513653999', 'Account Manager');
INSERT INTO sales_team_members (name, email, phone, designation) VALUES ('Heather Snow', 'juancampos@lloyd.org', '9143469773', 'Account Manager');
INSERT INTO sales_team_members (name, email, phone, designation) VALUES ('Emily Blair', 'wcastro@yahoo.com', '9648977048', 'Account Manager');
INSERT INTO sales_team_members (name, email, phone, designation) VALUES ('Martin Harris', 'qgrimes@gmail.com', '9534794718', 'Account Manager');
INSERT INTO sales_team_members (name, email, phone, designation) VALUES ('Kimberly Smith', 'salazarmaria@yahoo.com', '9611742081', 'Account Manager');
INSERT INTO sales_team_members (name, email, phone, designation) VALUES ('Frederick Harrell', 'johnponce@west.net', '9726401695', 'Sales Executive');
INSERT INTO sales_team_members (name, email, phone, designation) VALUES ('Mrs. Elizabeth Carter MD', 'tamaramorrison@hotmail.com', '9641903389', 'Sales Executive');
INSERT INTO sales_team_members (name, email, phone, designation) VALUES ('Brandon Yates', 'kellylopez@gmail.com', '9402621084', 'Sales Executive');
INSERT INTO sales_team_members (name, email, phone, designation) VALUES ('William Green', 'sheltondavid@mclean.net', '9911538590', 'Sales Executive');
INSERT INTO sales_team_members (name, email, phone, designation) VALUES ('Sara Warren', 'pattylawrence@riley-hayes.com', '9763968655', 'Account Manager');
INSERT INTO sales_team_members (name, email, phone, designation) VALUES ('Louis Tucker', 'johndennis@gmail.com', '9671835844', 'BD Manager');
INSERT INTO sales_team_members (name, email, phone, designation) VALUES ('Jacqueline Jackson', 'garciadustin@hotmail.com', '9969964135', 'BD Manager');
INSERT INTO sales_team_members (name, email, phone, designation) VALUES ('Robert Walters', 'martinezjacob@wilson.com', '9257798602', 'Account Manager');
INSERT INTO sales_team_members (name, email, phone, designation) VALUES ('Alex Woodward', 'mendozajessica@giles.net', '9206046331', 'BD Manager');
INSERT INTO sales_team_members (name, email, phone, designation) VALUES ('Brian Green', 'lucasmichael@brown.com', '9179180332', 'BD Manager');
INSERT INTO sales_team_members (name, email, phone, designation) VALUES ('Melissa Myers', 'rebecca79@gmail.com', '9454546567', 'Account Manager');
INSERT INTO sales_team_members (name, email, phone, designation) VALUES ('Christina Saunders', 'matthewking@morse.biz', '9701095367', 'Sales Executive');
INSERT INTO sales_team_members (name, email, phone, designation) VALUES ('Shelly Lowery', 'qmonroe@gmail.com', '9479880545', 'Account Manager');
INSERT INTO sales_team_members (name, email, phone, designation) VALUES ('Alexandria Harmon', 'stephensdennis@yahoo.com', '9439513621', 'BD Manager');
INSERT INTO sales_team_members (name, email, phone, designation) VALUES ('Dwayne Howard', 'paul61@wheeler.com', '9787649391', 'Sales Executive');
INSERT INTO clients (client_name, industry, domain, website_url, contact_email, sales_person_id) VALUES ('Allen Ltd', 'Education', 'Automation', 'https://gray-hutchinson.org', 'sjohnson@barnes.info', 17);
INSERT INTO clients (client_name, industry, domain, website_url, contact_email, sales_person_id) VALUES ('Green and Sons', 'Education', 'Automation', 'https://rose-freeman.net', 'hensontroy@monroe-williams.biz', 4);
INSERT INTO clients (client_name, industry, domain, website_url, contact_email, sales_person_id) VALUES ('Dunn Ltd', 'Education', 'SaaS', 'https://monroe.com', 'aherring@smith-smith.com', 5);
INSERT INTO clients (client_name, industry, domain, website_url, contact_email, sales_person_id) VALUES ('Rice, Davis and Wilson', 'Logistics', 'Analytics', 'https://gonzalez.com', 'alvarezsandra@miller.com', 3);
INSERT INTO clients (client_name, industry, domain, website_url, contact_email, sales_person_id) VALUES ('Anderson-Meyer', 'Education', 'Automation', 'https://newman.com', 'williamserin@edwards.com', 13);
INSERT INTO clients (client_name, industry, domain, website_url, contact_email, sales_person_id) VALUES ('Ali, Lawson and Simpson', 'FinTech', 'Analytics', 'https://orr.net', 'jaredmatthews@taylor.com', 13);
INSERT INTO clients (client_name, industry, domain, website_url, contact_email, sales_person_id) VALUES ('Clarke-Higgins', 'Healthcare', 'SaaS', 'https://chan-johnson.com', 'edwardsilva@foster-kelley.com', 21);
INSERT INTO clients (client_name, industry, domain, website_url, contact_email, sales_person_id) VALUES ('Woods and Sons', 'FinTech', 'SaaS', 'https://parker.com', 'richard54@rodriguez-hoffman.info', 7);
INSERT INTO clients (client_name, industry, domain, website_url, contact_email, sales_person_id) VALUES ('Rogers-Yates', 'Education', 'Automation', 'https://martinez-wilson.info', 'vjohnson@mcdaniel.org', 5);
INSERT INTO clients (client_name, industry, domain, website_url, contact_email, sales_person_id) VALUES ('Drake-Frey', 'Healthcare', 'Automation', 'https://jones.com', 'brucesmith@hawkins-roberts.info', 19);
INSERT INTO clients (client_name, industry, domain, website_url, contact_email, sales_person_id) VALUES ('Klein, Robinson and Miller', 'Logistics', 'SaaS', 'https://hinton.org', 'ryanhoward@short.com', 12);
INSERT INTO clients (client_name, industry, domain, website_url, contact_email, sales_person_id) VALUES ('Hayes, Rhodes and Wilson', 'Education', 'Automation', 'https://scott-davidson.com', 'danielellis@payne-hernandez.org', 6);
INSERT INTO clients (client_name, industry, domain, website_url, contact_email, sales_person_id) VALUES ('Hernandez-Sullivan', 'Education', 'Automation', 'https://henderson.com', 'obolton@baxter.com', 20);
INSERT INTO clients (client_name, industry, domain, website_url, contact_email, sales_person_id) VALUES ('Thornton-Burgess', 'FinTech', 'Analytics', 'https://meyers-johnson.com', 'carrie26@phillips.com', 20);
INSERT INTO clients (client_name, industry, domain, website_url, contact_email, sales_person_id) VALUES ('Melton, Williams and Perez', 'Education', 'Automation', 'https://turner.com', 'laurenmelton@schmitt-wagner.net', 17);
INSERT INTO clients (client_name, industry, domain, website_url, contact_email, sales_person_id) VALUES ('Johnson, Davis and Bauer', 'Healthcare', 'Analytics', 'https://chang.com', 'amanda96@bruce-compton.org', 15);
INSERT INTO clients (client_name, industry, domain, website_url, contact_email, sales_person_id) VALUES ('Hall, Hancock and Smith', 'Retail', 'Analytics', 'https://yang.net', 'marvin74@barton-cruz.biz', 10);
INSERT INTO clients (client_name, industry, domain, website_url, contact_email, sales_person_id) VALUES ('Martin and Sons', 'Retail', 'SaaS', 'https://mitchell.com', 'olsondonald@love.com', 9);
INSERT INTO clients (client_name, industry, domain, website_url, contact_email, sales_person_id) VALUES ('Johnson-Owens', 'FinTech', 'SaaS', 'https://williams-ruiz.com', 'johnsonchristina@nguyen.com', 22);
INSERT INTO clients (client_name, industry, domain, website_url, contact_email, sales_person_id) VALUES ('Logan-Waters', 'Retail', 'Automation', 'https://ibarra.info', 'debra94@mullen.com', 5);
INSERT INTO client_requirements (client_id, title, description, business_challenges) VALUES (5, 'User-friendly systemic workforce', 'Team yet although hot he couple ground. Away and various main too war project occur.', 'transform next-generation partnerships');
INSERT INTO client_requirements (client_id, title, description, business_challenges) VALUES (7, 'Cross-platform intangible time-frame', 'Social issue indicate. Try while reveal bad audience grow ahead.', 'enhance B2B ROI');
INSERT INTO client_requirements (client_id, title, description, business_challenges) VALUES (7, 'Persevering bifurcated matrices', 'Candidate whom gun list fall. Player contain year bill ok choose today. Source firm drug senior.', 'incentivize visionary functionalities');
INSERT INTO client_requirements (client_id, title, description, business_challenges) VALUES (4, 'Multi-layered scalable moderator', 'Impact individual rock fly daughter fall. Before control board born painting child reflect.', 'evolve rich e-services');
INSERT INTO client_requirements (client_id, title, description, business_challenges) VALUES (5, 'Quality-focused well-modulated initiative', 'Worker building this American either moment ok how. Second government the pull.', 'whiteboard best-of-breed users');
INSERT INTO client_requirements (client_id, title, description, business_challenges) VALUES (20, 'Customer-focused incremental productivity', 'Seem explain black leave. Himself former possible reach challenge value.', 'integrate bleeding-edge functionalities');
INSERT INTO client_requirements (client_id, title, description, business_challenges) VALUES (15, 'Configurable contextually-based hierarchy', 'Do father beautiful than. Sign third in approach recent.', 'transform strategic vortals');
INSERT INTO client_requirements (client_id, title, description, business_challenges) VALUES (19, 'Inverse national knowledgebase', 'Floor itself news experience must cut. Since method left plant evening.', 'architect front-end web services');
INSERT INTO client_requirements (client_id, title, description, business_challenges) VALUES (11, 'Adaptive user-facing monitoring', 'Present produce manager well lose finish summer. Case I course first factor.', 'drive B2C convergence');
INSERT INTO client_requirements (client_id, title, description, business_challenges) VALUES (19, 'Ameliorated mobile product', 'Drop actually watch. At artist will institution throughout describe.', 'repurpose B2B infrastructures');
INSERT INTO client_requirements (client_id, title, description, business_challenges) VALUES (10, 'Managed disintermediate conglomeration', 'What to sea. Collection bad until our per leader change.', 'syndicate robust users');
INSERT INTO client_requirements (client_id, title, description, business_challenges) VALUES (9, 'Re-engineered neutral firmware', 'House build get anything event yet effect.', 'leverage clicks-and-mortar eyeballs');
INSERT INTO client_requirements (client_id, title, description, business_challenges) VALUES (21, 'Re-contextualized 6thgeneration intranet', 'Upon we lose water stand single. Could nature interest wear community college probably church.', 'generate user-centric eyeballs');
INSERT INTO client_requirements (client_id, title, description, business_challenges) VALUES (16, 'Adaptive web-enabled migration', 'His less already treatment PM sometimes set. Gun word citizen.', 'unleash mission-critical solutions');
INSERT INTO client_requirements (client_id, title, description, business_challenges) VALUES (21, 'Down-sized leadingedge architecture', 'Provide other identify fill art by. Treat relate respond rich.', 'target B2C systems');
INSERT INTO client_requirements (client_id, title, description, business_challenges) VALUES (11, 'Reactive coherent alliance', 'We ask benefit ago again. Pattern president add lead network the.', 'integrate clicks-and-mortar architectures');
INSERT INTO client_requirements (client_id, title, description, business_challenges) VALUES (17, 'Mandatory cohesive neural-net', 'Company TV policy drug. Foreign agency when personal huge difficult player forget.', 'unleash virtual eyeballs');
INSERT INTO client_requirements (client_id, title, description, business_challenges) VALUES (18, 'Ameliorated 4thgeneration Graphic Interface', 'Require agree inside thank.', 'envisioneer user-centric paradigms');
INSERT INTO client_requirements (client_id, title, description, business_challenges) VALUES (14, 'Synergized incremental flexibility', 'Next according television next sense make real use. Girl sister their rate drop marriage worker.', 'enhance front-end solutions');
INSERT INTO client_requirements (client_id, title, description, business_challenges) VALUES (5, 'User-friendly zero-defect matrices', 'Upon full director race. Let left very your stock determine.', 'implement enterprise users');
INSERT INTO projects (project_name, category, estimated_duration_weeks, required_experience_years, client_id, client_requirement_id) VALUES ('Implement End-To-End Initiatives', 'CustomDev', 15, 1.8, 21, 13);
INSERT INTO projects (project_name, category, estimated_duration_weeks, required_experience_years, client_id, client_requirement_id) VALUES ('Transition 24/365 Infrastructures', 'MobileApp', 9, 1.5, 11, 6);
INSERT INTO projects (project_name, category, estimated_duration_weeks, required_experience_years, client_id, client_requirement_id) VALUES ('Extend Plug-And-Play Solutions', 'MobileApp', 11, 3.9, 13, 16);
INSERT INTO projects (project_name, category, estimated_duration_weeks, required_experience_years, client_id, client_requirement_id) VALUES ('Iterate Clicks-And-Mortar Deliverables', 'LowCode', 7, 3.8, 10, 4);
INSERT INTO projects (project_name, category, estimated_duration_weeks, required_experience_years, client_id, client_requirement_id) VALUES ('Productize Next-Generation Partnerships', 'LowCode', 6, 1.9, 9, 22);
INSERT INTO projects (project_name, category, estimated_duration_weeks, required_experience_years, client_id, client_requirement_id) VALUES ('Incubate Virtual E-Services', 'LowCode', 12, 1.8, 6, 4);
INSERT INTO projects (project_name, category, estimated_duration_weeks, required_experience_years, client_id, client_requirement_id) VALUES ('Enhance Next-Generation Architectures', 'LowCode', 9, 4.4, 8, 6);
INSERT INTO projects (project_name, category, estimated_duration_weeks, required_experience_years, client_id, client_requirement_id) VALUES ('Syndicate Clicks-And-Mortar E-Commerce', 'DevOps', 9, 3.7, 4, 3);
INSERT INTO projects (project_name, category, estimated_duration_weeks, required_experience_years, client_id, client_requirement_id) VALUES ('Architect Enterprise Paradigms', 'DevOps', 15, 1.8, 11, 5);
INSERT INTO projects (project_name, category, estimated_duration_weeks, required_experience_years, client_id, client_requirement_id) VALUES ('Re-Intermediate Real-Time Web-Readiness', 'MobileApp', 7, 3.4, 14, 16);
INSERT INTO projects (project_name, category, estimated_duration_weeks, required_experience_years, client_id, client_requirement_id) VALUES ('Benchmark Cross-Media Relationships', 'MobileApp', 6, 3.0, 4, 22);
INSERT INTO projects (project_name, category, estimated_duration_weeks, required_experience_years, client_id, client_requirement_id) VALUES ('Transition Cross-Platform Methodologies', 'LowCode', 17, 4.5, 9, 11);
INSERT INTO projects (project_name, category, estimated_duration_weeks, required_experience_years, client_id, client_requirement_id) VALUES ('Target Global Metrics', 'CustomDev', 20, 3.7, 21, 8);
INSERT INTO projects (project_name, category, estimated_duration_weeks, required_experience_years, client_id, client_requirement_id) VALUES ('Mesh E-Business Portals', 'MobileApp', 18, 1.7, 8, 8);
INSERT INTO projects (project_name, category, estimated_duration_weeks, required_experience_years, client_id, client_requirement_id) VALUES ('Transform Sticky Niches', 'CustomDev', 14, 2.3, 22, 17);
INSERT INTO projects (project_name, category, estimated_duration_weeks, required_experience_years, client_id, client_requirement_id) VALUES ('Utilize B2B E-Business', 'MobileApp', 6, 2.9, 16, 21);
INSERT INTO projects (project_name, category, estimated_duration_weeks, required_experience_years, client_id, client_requirement_id) VALUES ('Revolutionize Global Architectures', 'CustomDev', 16, 2.6, 11, 7);
INSERT INTO projects (project_name, category, estimated_duration_weeks, required_experience_years, client_id, client_requirement_id) VALUES ('Architect Turn-Key Solutions', 'LowCode', 13, 3.7, 13, 4);
INSERT INTO projects (project_name, category, estimated_duration_weeks, required_experience_years, client_id, client_requirement_id) VALUES ('Deploy 24/7 Schemas', 'CustomDev', 8, 2.2, 18, 14);
INSERT INTO projects (project_name, category, estimated_duration_weeks, required_experience_years, client_id, client_requirement_id) VALUES ('Transform Collaborative Initiatives', 'CustomDev', 16, 2.6, 22, 7);
INSERT INTO skills (skill_name) VALUES ('Sales');
INSERT INTO skills (skill_name) VALUES ('Product/process');
INSERT INTO skills (skill_name) VALUES ('Psychotherapist,');
INSERT INTO skills (skill_name) VALUES ('Editor,');
INSERT INTO skills (skill_name) VALUES ('Programme');
INSERT INTO skills (skill_name) VALUES ('Sports');
INSERT INTO skills (skill_name) VALUES ('Librarian,');
INSERT INTO skills (skill_name) VALUES ('Conservation');
INSERT INTO skills (skill_name) VALUES ('Pension');
INSERT INTO skills (skill_name) VALUES ('Forest/woodland');
INSERT INTO skills (skill_name) VALUES ('Multimedia');
INSERT INTO skills (skill_name) VALUES ('Careers');
INSERT INTO skills (skill_name) VALUES ('Systems');
INSERT INTO skills (skill_name) VALUES ('Risk');
INSERT INTO skills (skill_name) VALUES ('Legal');
INSERT INTO skills (skill_name) VALUES ('Facilities');
INSERT INTO skills (skill_name) VALUES ('Professor');
INSERT INTO skills (skill_name) VALUES ('Fish');
INSERT INTO skills (skill_name) VALUES ('Make');
INSERT INTO skills (skill_name) VALUES ('Quarry');
INSERT INTO employees (name, designation, department, availability_status) VALUES ('Jennifer Griffin', 'Accounting technician', 'DevOps', 'Engaged');
INSERT INTO employees (name, designation, department, availability_status) VALUES ('Tina Rowe', 'Environmental manager', 'Design', 'On Leave');
INSERT INTO employees (name, designation, department, availability_status) VALUES ('David Alvarez', 'Estate agent', 'Engineering', 'Available');
INSERT INTO employees (name, designation, department, availability_status) VALUES ('Ian Tucker', 'Database administrator', 'QA', 'On Leave');
INSERT INTO employees (name, designation, department, availability_status) VALUES ('Kelly Miller', 'Hydrologist', 'DevOps', 'Available');
INSERT INTO employees (name, designation, department, availability_status) VALUES ('Lynn Martinez', 'Barristers clerk', 'QA', 'Available');
INSERT INTO employees (name, designation, department, availability_status) VALUES ('Andrew Berg', 'Designer, multimedia', 'Design', 'Engaged');
INSERT INTO employees (name, designation, department, availability_status) VALUES ('Julie Byrd', 'Paramedic', 'Design', 'Available');
INSERT INTO employees (name, designation, department, availability_status) VALUES ('Christopher Williams DVM', 'Librarian, academic', 'Design', 'On Leave');
INSERT INTO employees (name, designation, department, availability_status) VALUES ('Melanie Meyer', 'Land', 'Design', 'On Leave');
INSERT INTO employees (name, designation, department, availability_status) VALUES ('Thomas Marquez', 'Therapist, music', 'Engineering', 'Available');
INSERT INTO employees (name, designation, department, availability_status) VALUES ('Brittany Barker', 'Research officer, political party', 'Design', 'Available');
INSERT INTO employees (name, designation, department, availability_status) VALUES ('Laura Lewis', 'Prison officer', 'DevOps', 'On Leave');
INSERT INTO employees (name, designation, department, availability_status) VALUES ('John Munoz', 'Investment banker, corporate', 'QA', 'Engaged');
INSERT INTO employees (name, designation, department, availability_status) VALUES ('Christina Williams', 'Contractor', 'Design', 'On Leave');
INSERT INTO employees (name, designation, department, availability_status) VALUES ('Shane Bishop', 'Clinical embryologist', 'Engineering', 'Available');
INSERT INTO employees (name, designation, department, availability_status) VALUES ('Nicole Coleman', 'Historic buildings inspector/conservation officer', 'Design', 'Engaged');
INSERT INTO employees (name, designation, department, availability_status) VALUES ('Gina Jennings', 'Development worker, community', 'DevOps', 'Engaged');
INSERT INTO employees (name, designation, department, availability_status) VALUES ('Ryan Robbins', 'Nurse, adult', 'Engineering', 'Engaged');
INSERT INTO employees (name, designation, department, availability_status) VALUES ('Matthew Singleton', 'Psychotherapist', 'QA', 'On Leave');
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (7, 13, 4.9, 4.1);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (18, 19, 1.0, 3.5);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (5, 25, 3.4, 3.8);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (24, 15, 4.5, 3.9);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (10, 12, 2.9, 4.9);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (7, 9, 2.1, 4.2);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (8, 17, 1.5, 4.3);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (16, 12, 4.5, 3.9);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (5, 10, 1.2, 4.5);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (22, 19, 4.8, 4.9);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (6, 28, 3.6, 4.6);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (19, 22, 2.5, 4.3);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (11, 21, 3.3, 3.5);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (9, 17, 2.3, 4.7);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (7, 19, 4.1, 3.6);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (13, 14, 1.6, 4.4);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (16, 21, 5.0, 3.7);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (8, 24, 3.9, 4.9);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (14, 14, 4.4, 4.6);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (14, 21, 4.3, 3.9);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (8, 12, 3.2, 4.2);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (15, 19, 1.5, 3.7);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (20, 22, 1.2, 4.0);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (9, 14, 3.5, 4.1);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (7, 11, 4.2, 3.8);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (12, 10, 2.5, 3.6);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (22, 25, 2.2, 4.9);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (23, 15, 2.7, 4.1);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (13, 27, 4.1, 4.1);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (16, 12, 1.3, 4.8);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (5, 25, 2.8, 4.5);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (8, 24, 2.6, 3.8);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (6, 15, 3.5, 3.7);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (19, 21, 2.4, 4.7);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (8, 28, 4.9, 3.7);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (17, 22, 4.5, 4.2);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (15, 24, 5.0, 4.5);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (11, 26, 3.4, 3.8);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (15, 19, 4.3, 3.6);
INSERT INTO employee_skills (employee_id, skill_id, experience_years, confidence_rating) VALUES (9, 17, 3.4, 3.7);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (15, 27, 1.6);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (18, 11, 2.6);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (19, 10, 1.1);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (7, 10, 1.6);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (17, 19, 2.7);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (7, 23, 2.9);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (19, 21, 2.8);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (19, 10, 2.1);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (19, 28, 3.0);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (16, 15, 1.6);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (22, 22, 2.7);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (18, 21, 2.2);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (10, 9, 2.3);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (3, 14, 1.6);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (21, 17, 1.7);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (18, 17, 2.9);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (12, 22, 1.8);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (15, 10, 1.3);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (7, 16, 1.6);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (13, 10, 2.9);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (18, 22, 1.3);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (22, 11, 2.3);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (7, 20, 1.8);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (22, 23, 1.8);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (4, 12, 1.9);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (7, 9, 1.1);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (22, 13, 2.3);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (6, 26, 2.3);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (9, 21, 2.6);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (18, 12, 2.8);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (22, 23, 2.2);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (13, 12, 2.9);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (22, 18, 2.6);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (7, 21, 2.6);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (6, 25, 2.7);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (9, 10, 2.6);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (17, 20, 2.5);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (17, 20, 2.6);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (5, 10, 2.8);
INSERT INTO project_techstack (project_id, skill_id, min_experience_required) VALUES (4, 24, 1.5);